version: "1.8.2-SNAPSHOT"
language:
  type: "en_us"
  by_player: true
database:
  ignore_existing_driver: false
  type: "H2"
  name: "flectonepulse"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "1234"
  parameters: "?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8"
  prefix: ""
proxy:
  clusters: []
  bungeecord: false
  velocity: false
  redis:
    enable: false
    host: "127.0.0.1"
    port: 6379
    ssl: false
    user: ""
    password: ""
command:
  unregister_on_reload: false
  disabled_fabric:
  - "msg"
  - "banlist"
  - "kick"
  - "w"
  - "tell"
  - "me"
  - "pardon"
  - "ban"
module:
  enable: true
  use_paper_message_sender: false
  use_bukkit_pre_login_listener: false
editor:
  host: ""
  https: false
  port: 25566
logger:
  console: "Console"
  prefix: "\e[38;2;77;166;255m(FlectonePulse) \e[0m"
  description:
    - "\e[38;2;77;166;255m ___       ___  __  ___  __        ___ \e[0m"
    - "\e[38;2;77;166;255m|__  |    |__  /  `  |  /  \\ |\\ | |__  \e[0m"
    - "\e[38;2;77;166;255m|    |___ |___ \\__,  |  \\__/ | \\| |___ \e[0m"
    - "\e[38;2;77;166;255m __             __   ___ \e[0m"
    - "\e[38;2;77;166;255m|__) |  | |    /__` |__  \e[0m"
    - "\e[38;2;77;166;255m|    \\__/ |___ .__/ |___\e[38;2;77;166;255m   /\\\e[0m"
    - "\e[38;2;77;166;255m                          /  \\ v<version>\e[0m"
    - "\e[38;2;77;166;255m__/\\___  ____/\\_____  ___/    \\______ \e[0m"
    - "\e[38;2;77;166;255m       \\/           \\/  \e[0m"
  warn: "\e[0;93m"
  info: "\e[38;2;166;216;255m"
  filter:
  - "Paper Async Command Builder"
  - "Caught previously unhandled exception :"
  - "Error received from Telegram GetUpdates Request"
  - "OkHttp TaskRunner"
  - "Exception in thread \"ForkJoinPool"
  - "FlectonePulseDatabase - "
cache:
  types:
    COOLDOWN:
      invalidate_on_reload: false
      duration: 5
      time_unit: "HOURS"
      size: 5000
    DIALOG_CLICK:
      invalidate_on_reload: false
      duration: 1
      time_unit: "SECONDS"
      size: 100
    OFFLINE_PLAYERS:
      invalidate_on_reload: false
      duration: 1
      time_unit: "HOURS"
      size: 1000
    MODERATION:
      invalidate_on_reload: false
      duration: 1
      time_unit: "HOURS"
      size: 5000
    LEGACY_COLOR_MESSAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 100000
    MENTION_MESSAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 1000
    SWEAR_MESSAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 100000
    REPLACEMENT_MESSAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 100000
    REPLACEMENT_IMAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 100
    TRANSLATE_MESSAGE:
      invalidate_on_reload: false
      duration: 1
      time_unit: "HOURS"
      size: 5000
    PROFILE_PROPERTY:
      invalidate_on_reload: false
      duration: 1
      time_unit: "HOURS"
      size: 1000
metrics:
  enable: true
