enable: true
afk:
  enable: true
  range: "SERVER"
  delay: 3000
  ignore:
  - "afk"
  destination:
    type: "CHAT"
  ticker:
    enable: true
    period: 20
  sound:
    enable: false
anvil:
  enable: false
auto:
  enable: false
  types:
    announcement:
      random: true
      destination:
        type: "CHAT"
      ticker:
        enable: true
        period: 9000
      sound:
        enable: false
book:
  enable: false
bossbar:
  enable: false
  announce: {}
brand:
  enable: false
  random: true
  destination:
    type: "BRAND"
  ticker:
    enable: true
    period: 100
bubble:
  enable: true
  visible_to_self: true
  max_count: 3
  max_length: 30
  elevation: 2.1
  distance: 30.0
  read_speed: 90.0
  handicap_chars: 10.0
  word_break_hint: "‑"
  interaction:
    enable: true
    height: 0.4
  modern:
    enable: true
    has_shadow: false
    see_through: true
    animation_time: 5
    scale: 1.0
    background: "#00000040"
    billboard: "CENTER"
  ticker:
    enable: true
    period: 5
chat:
  enable: true
  mode: "BUKKIT"
  priority: "NORMAL"
  types:
    local:
      enable: true
      cancel: true
      range: 100
      priority: 0
      trigger: ""
      null_receiver:
        enable: true
        destination:
          type: "ACTION_BAR"
          times:
            stay: 20
      destination:
        type: "CHAT"
      cooldown:
        enable: false
      sound:
        enable: false
    global:
      enable: true
      cancel: false
      range: "PROXY"
      priority: 5
      trigger: "!"
      null_receiver:
        enable: true
        destination:
          type: "ACTION_BAR"
          times:
            stay: 20
      destination:
        type: "CHAT"
      cooldown:
        enable: false
      sound:
        enable: false
format:
  enable: true
  convert_legacy_color: true
  adventure_tags:
  - "HOVER"
  - "CLICK"
  - "COLOR"
  - "KEYBIND"
  - "TRANSLATABLE"
  - "TRANSLATABLE_FALLBACK"
  - "INSERTION"
  - "FONT"
  - "DECORATION"
  - "GRADIENT"
  - "RAINBOW"
  - "RESET"
  - "NEWLINE"
  - "TRANSITION"
  - "SELECTOR"
  - "SCORE"
  - "NBT"
  - "PRIDE"
  - "SHADOW_COLOR"
  fcolor:
    enable: true
    default_colors:
      1: "<gradient:#A6D8FF:#8CC8FF>"
      2: "<gradient:#6BB6FF:#4DA6FF>"
      3: "#A9A9A9"
      4: "#FFFAFA"
  fixation:
    enable: false
    end_dot: false
    first_letter_uppercase: false
    non_dot_symbols:
    - ";"
    - ":"
    - "'"
    - "\""
    - ","
    - "?"
    - "!"
    - "."
  mention:
    enable: true
    trigger: "@"
    everyone_tag: "here"
    destination:
      type: "TOAST"
      icon: "minecraft:bell"
      subtext: ""
      style: "TASK"
    sound:
      enable: true
      volume: 0.9
      pitch: 1.5
      category: "UI"
      name: "SFX_Drop_Items_Potion"
  moderation:
    enable: true
    caps:
      enable: false
      trigger: 0.7
    delete:
      enable: false
      history_length: 100
    newbie:
      enable: false
      mode: "PLAYED_TIME"
      timeout: 3600
    flood:
      enable: false
      trim_to_single: false
      max_repeated_symbols: 10
      max_repeated_words: 2
    swear:
      enable: false
      ignore:
      - "тебя"
      - "тебе"
      trigger:
      - "((у|[нз]а|(хитро|не)?вз?[ыьъ]|с[ьъ]|(и|ра)[зс]ъ?|(о[тб]|под)[ьъ]?|(.\\B)+?[оаеи])?-?([её]б(?!о[рй])|и[пб][ае][тц]).*?|(н[иеа]|([дп]|верт)о|ра[зс]|з?а|с(ме)?|о(т|дно)?|апч)?-?ху([яйиеёю]|ли(?!ган)).*?|(в[зы]|(три|два|четыре)жды|(н|сук)а)?-?бл(я(?!(х|ш[кн]|мб)[ауеыио]).*?|[еэ][дт]ь?)|(ра[сз]|[зн]а|[со]|вы?|п(ере|р[оие]|од)|и[зс]ъ?|[ао]т)?п[иеё]зд.*?|(за)?п[ие]д[аое]?р([оа]м|(ас)?(ну.*?|и(ли)?[нщктл]ь?)?|(о(ч[еи])?|ас)?к(ой)|юг)[ауеы]?|манд([ауеыи](л(и[сзщ])?[ауеиы])?|ой|[ао]вошь?(е?к[ауе])?|юк(ов|[ауи])?)|муд([яаио].*?|е?н([ьюия]|ей))|мля([тд]ь)?|лять|([нз]а|по|пи)х|м[ао]л[ао]фь([яию]|[еёо]й))(?=[\\s,.:;\"']|$)"
      - "(([уyu]|[нзnz3][аa]|(хитро|не)?[вvwb][зz3]?[ыьъi]|[сsc][ьъ']|(и|[рpr][аa4])[зсzs]ъ?|([оo0][тбtb6]|[пp][оo0][дd9])[ьъ']?|(.\\B)+?[оаеиeo])?-?([еёe][бb6](?!о[рй])|и[пб][ае][тц]).*?|([нn][иеаaie]|([дпdp]|[вv][еe3][рpr][тt])[оo0]|[рpr][аa][зсzc3]|[з3z]?[аa]|с(ме)?|[оo0]([тt]|дно)?|апч)?-?[хxh][уuy]([яйиеёюuie]|ли(?!ган)).*?|([вvw][зы3z]|(три|два|четыре)жды|(н|[сc][уuy][кk])[аa])?-?[бb6][лl]([яy](?!(х|ш[кн]|мб)[ауеыио]).*?|[еэe][дтdt][ь']?)|([рp][аa][сзc3z]|[знzn][аa]|[соsc]|[вv][ыi]?|[пp]([еe][рpr][еe]|[рrp][оиioеe]|[оo0][дd])|и[зс]ъ?|[аоao][тt])?[пpn][иеёieu][зz3][дd9].*?|([зz3][аa])?[пp][иеieu][дd][аоеaoe]?[рrp](ну.*?|[оаoa][мm]|([аa][сcs])?([иiu]([лl][иiu])?[нщктлtlsn]ь?)?|([оo](ч[еиei])?|[аa][сcs])?[кk]([оo]й)?|[юu][гg])[ауеыauyei]?|[мm][аa][нnh][дd]([ауеыayueiи]([лl]([иi][сзc3щ])?[ауеыauyei])?|[оo][йi]|[аоao][вvwb][оo](ш|sh)[ь']?([e]?[кk][ауеayue])?|юк(ов|[ауи])?)|[мm][уuy][дd6]([яyаиоaiuo0].*?|[еe]?[нhn]([ьюия'uiya]|ей))|мля([тд]ь)?|лять|([нз]а|по|пи)х|м[ао]л[ао]фь([яию]|[её]й))(?=[\\s,.:;\"']|$)"
  names:
    enable: true
    should_check_invisibility: false
  object:
    enable: false
    player_head: true
    sprite: true
    need_extra_space: true
  question_answer:
    enable: false
    questions:
      server:
        range: "PLAYER"
        destination:
          type: "CHAT"
        cooldown:
          enable: false
        sound:
          enable: false
        target: "(?i)\\b(what\\s+is\\s+this\\s+server|what\\'?s\\s+this\\s+server|what\\s+server\\s+is\\s+this)\\b"
      flectone:
        range: "PLAYER"
        destination:
          type: "CHAT"
        cooldown:
          enable: false
        sound:
          enable: false
        target: "(?i)\\b(flectone|flectonepulse|flecton)\\b"
  replacement:
    enable: true
    triggers:
      ping: "(?<!\\\\)(?<!\\S)%ping%(?!\\S)"
      tps: "(?<!\\\\)(?<!\\S)%tps%(?!\\S)"
      online: "(?<!\\\\)(?<!\\S)%online%(?!\\S)"
      coords: "(?<!\\\\)(?<!\\S)%coords%(?!\\S)"
      stats: "(?<!\\\\)(?<!\\S)%stats%(?!\\S)"
      skin: "(?<!\\\\)(?<!\\S)%skin%(?!\\S)"
      item: "(?<!\\\\)(?<!\\S)%item%(?!\\S)"
      image: "(?<!\\\\{2,})(?<=\\s|^)((?i:https?)://(?:[a-zA-Z0-9-@]{1,63}\\.)*(?i:imgur\\.com|discordapp\\.net|cdn\\.discordapp\\.com)/[\\w\\-./?=&%!#$'()*+,;=~@]*\\.(?:jpg|jpeg|png|gif|webp|bmp))(?!\\S)"
      url: "(?<!\\\\{2,})(?<=\\s|^)((?i:https?|ftp)://(?:[\\p{L}a-zA-Z0-9-@]{1,63}\\.)+[\\p{L}a-zA-Z]{2,6}(?::\\d{1,5})?(?:/[\\w\\-./?=&%!#$'()*+,;=~@]*)?)(?!\\S)"
      spoiler: "(?<!\\S)\\|\\|([^\\|\\|\\n]+)\\|\\|(?!\\S)"
      bold: "(?<!\\S)\\*\\*([^\\*\\*\\n]+)\\*\\*(?!\\S)"
      italic: "(?<!\\S)\\*([^\\*\\n]+)\\*(?!\\S)"
      underline: "(?<!\\S)__([^__\\n]+)__(?!\\S)"
      obfuscated: "(?<!\\S)\\?\\?([^\\?\\?\\n]+)\\?\\?(?!\\S)"
      strikethrough: "(?<!\\S)~~([^~~\\n]+)~~(?!\\S)"
  scoreboard:
    enable: false
    name_visible: false
    color: "<white>"
    prefix: "<vault_prefix><stream_prefix>"
    suffix: "<afk_suffix><vault_suffix>"
    ticker:
      enable: false
  translate:
    enable: true
  world:
    enable: true
    mode: "TYPE"
    ticker:
      enable: false
    values:
      default: "<color:#98FB98>"
greeting:
  enable: false
  destination:
    type: "CHAT"
  sound:
    enable: false
join:
  enable: true
  first: true
  range: "SERVER"
  destination:
    type: "CHAT"
  sound:
    enable: false
objective:
  enable: false
  belowname:
    enable: false
    mode: "PING"
    ticker:
      enable: true
      period: 100
  tabname:
    enable: false
    mode: "PING"
    ticker:
      enable: true
      period: 100
quit:
  enable: true
  range: "SERVER"
  destination:
    type: "CHAT"
  sound:
    enable: false
rightclick:
  enable: true
  should_check_sneaking: false
  hide_name_when_invisible: true
  range: "PLAYER"
  destination:
    type: "ACTION_BAR"
    times:
      stay: 60
  cooldown:
    enable: false
  sound:
    enable: false
sidebar:
  enable: false
  random: true
  ticker:
    enable: true
    period: 100
sign:
  enable: false
status:
  enable: false
  icon:
    enable: false
    random: true
    values:
    - "server-icon-1.png"
    - "server-icon-2.png"
  motd:
    enable: true
    random: true
  players:
    enable: false
    control: true
    max: 69
    online: -69
  version:
    enable: false
    protocol: -1
tab:
  enable: false
  header:
    enable: false
    random: true
    destination:
      type: "TAB_HEADER"
    ticker:
      enable: true
      period: 100
  footer:
    enable: false
    random: true
    destination:
      type: "TAB_FOOTER"
    ticker:
      enable: true
      period: 100
  playerlistname:
    enable: false
    proxy_mode: true
    ticker:
      enable: true
      period: 100
update:
  enable: true
  destination:
    type: "CHAT"
  sound:
    enable: false
vanilla:
  enable: true
  types:
    - name: "DEATH"
      multi_message: true
      range: "SERVER"
      translation_keys:
        - "server.death.player"
        - "server.death.player.killedBy"
